name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # 每天運行一次
  workflow_dispatch: # 手動觸發

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
